# Array in numpy

Its a multiDimensional Array library were we can store the data in 1D,2D and 3D

In [10]:
import numpy as np
# can create 1D array by passing a list into .array func
a = np.array([1,2,3])
a

array([1, 2, 3])

numpy array is bettter then list as it takes up less memory, with faster execution and convinient

In [5]:
# np.array we can do a1*a2
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1*a2
# bet list cant dO THAT!

array([ 4, 10, 18])

In [19]:
#  2D array tp pass a list within a list

b = np.array([[1,2,3],[4,5,6]], dtype = "int8")
b

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [11]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [14]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [22]:
# Get type
print(a.dtype)
print(b.dtype)

int32
int8


# Accessing rows, columns and etc

In [29]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,14,13]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 14, 13]])

In [30]:
# get specific element in 2d arrar
a[1,3]

11

In [36]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
# get a specific column
a[:,2]

array([ 3, 10])

In [40]:
# to print the elements 2 to 6 in 'a' array
a[0,1:6]

array([2, 3, 4, 5, 6])

In [46]:
# we can change elements
a[1,3] = 69
print(a[1,3])

69
69


In [49]:
# we can change entire rows as well
a[0,:] = [91,92,93,94,95,96,97]
a

array([[91, 92, 93, 94, 95, 96, 97],
       [ 8,  9, 10, 69, 12, 14, 13]])

In [54]:
# for columns 
a[:,3] = [96,96]
a

array([[91, 92, 93, 96, 95, 96, 97],
       [ 8,  9, 10, 96, 12, 14, 13]])

In [60]:
# In 3D array
c= np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
# to access a specifi element 4 (work outside in)
c[1,0,1]

6

In [70]:
# get the rows
c[1,0,:]

array([5, 6])

In [74]:
#  change the elemenmt
c[1,1,1] = 9
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 9]]])

In [75]:
# get the column
c[1,:,1]

array([6, 9])

# Initilize Different typyes of arrays

In [4]:
# All 0s 
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# All 1s
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
# Any other element
np.full((2,2),69)

array([[69, 69],
       [69, 69]])

In [7]:
# Random numbers
np.random.rand(4,4)

array([[0.15953792, 0.85449645, 0.2018413 , 0.4478982 ],
       [0.89034029, 0.18449227, 0.12982229, 0.97521241],
       [0.35136526, 0.33097752, 0.2202738 , 0.78262133],
       [0.05412463, 0.19456889, 0.52727944, 0.73955698]])

In [11]:
np.random.randint(7,size=(4,4))

array([[4, 2, 3, 3],
       [4, 4, 5, 6],
       [5, 6, 6, 6],
       [5, 3, 3, 4]])

In [96]:
# Idenetity Matrix (it's a square matrix)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Q. build a matrix 

In [108]:
q = np.full((5,5),1)
q[1:4,1:4] = 0
q[2,2] = 9
print(q)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [119]:
#  copying array
a = [1,2,3]
b = a          # its not actually copying but its just pointing variable
b[0] = 7
print(b)

#  copy
d = [1,2,3]
c = d.copy()
print(d)

[7, 2, 3]
[1, 2, 3]


# Mathematics

In [139]:
a = np.array([1,2,3,4,5])
b = np .array([5,6,7,8,9])
a

array([1, 2, 3, 4, 5])

In [140]:
a + 2

array([3, 4, 5, 6, 7])

In [141]:
a - 2

array([-1,  0,  1,  2,  3])

In [142]:
a * 2

array([ 2,  4,  6,  8, 10])

In [143]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [144]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [135]:
a + b

array([ 6,  8, 10, 12, 14])

In [150]:
# Take sin and cosin

print(np.sin(90))
print(np.cos(45))
print(np.tan(30))

0.8939966636005579
0.5253219888177297
-6.405331196646276


In [151]:
 dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

 Linear Algebra

In [156]:
# Multpyling two matrix
a = np.full((2,3),3)
print(a)

b = np.random.randint(7,size=(3,2))
print(b)

# to mtultiply two matrix use matmul func
c = np.matmul(a,b)
c

[[3 3 3]
 [3 3 3]]
[[5 0]
 [1 3]
 [6 6]]


array([[36, 27],
       [36, 27]])

In [163]:
# finfd the diterminenet
d = np.identity(3)
np.linalg.det(d)

1.0

#### Statistics

In [178]:
a = np.array(([1,2,3,4,5,6,7,8,9,10],[15,44,75,36,0,35,93,55,42,71]))
np.mean(a)

26.05

In [179]:
a.max()

93

In [189]:
np.sum(a)

521

In [180]:
a.min()

0

In [184]:
np.max(a,axis = 1)

array([10, 93])

In [188]:
a.sum(axis = 0)

array([ 16,  46,  78,  40,   5,  41, 100,  63,  51,  81])

In [190]:
np.median(a)

9.5

In [193]:
np.mean(a,axis = 1)

array([ 5.5, 46.6])

Reshaping array

In [198]:
b = np.array(([1,2,3,4],[5,6,7,8]))
print(b)
print()
a = b.reshape((4,2))
print(a)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [203]:
# Vertically Stack

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1)
print(v2)

np.vstack([v1,v2])

[1 2 3 4]
[5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [205]:
#  horixantal stack
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

#### Load Data from file

In [24]:
fd = np.genfromtxt("num.txt", delimiter = ',')
fd = fd.astype('int32')
fd

array([10, 12, 21, 18, 20, 43, 43, 13, 28, 42, 40, 48, 22, 16, 46, 32, 42,
        9, 17, 33, 20, 34, 18, 33,  7])

#### Boolean Masking

In [34]:
fd > 40

array([False, False, False, False, False,  True,  True, False, False,
        True, False,  True, False, False,  True, False,  True, False,
       False, False, False, False, False, False, False])

In [35]:
# to get the values greater than 50
fd[fd>40]

array([43, 43, 42, 48, 46, 42])

In [44]:
np.any(fd > 40, axis = 0)

True

In [48]:
((fd > 30) & (fd < 45))

array([False, False, False, False, False,  True,  True, False, False,
        True,  True, False, False, False, False,  True,  True, False,
       False,  True, False,  True, False,  True, False])

Q. Index an array

In [235]:
c = np.full((6,5), 1)
c[2:4,:2] = 69
c

array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [69, 69,  1,  1,  1],
       [69, 69,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1]])

In [233]:
c = np.full((6,5), 0)
c[[0,1,2,3],[1,2,3,4]] = 9
c

array([[0, 9, 0, 0, 0],
       [0, 0, 9, 0, 0],
       [0, 0, 0, 9, 0],
       [0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [232]:
c = np.full((6,5), 1)
c[[0,4,5],3:] = 7
c

array([[1, 1, 1, 7, 7],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 7, 7],
       [1, 1, 1, 7, 7]])