####  Q. Multiply two Matrix

In [1]:
import numpy as np

In [4]:
a = np.array(([1,2,3,4],[5,6,7,8]))
np.shape(a)

(2, 4)

In [6]:
b = np.array(([9,8],[7,6],[5,4],[3,2]))
np.shape(b)

(4, 2)

In [8]:
np.matmul(a,b)

array([[ 50,  40],
       [146, 120]])

If the numbe rof rows and columns are same in both matrix then we can directly do m * n

In [11]:
m = np.array(([1,2,3,4],[5,6,7,8]))
n = np.array(([9,8,7,6],[5,4,3,2]))

In [12]:
print(np.shape(m))
print(np.shape(n))

(2, 4)
(2, 4)


In [13]:
m * n

array([[ 9, 16, 21, 24],
       [25, 24, 21, 16]])

#### Q. Create a program to change a string element in a specified numpy array to uppercase to lower case, capitalise the first letter, title - case or swapcase

In [48]:
larr = np.array(["ahad",'fahad','tina','zaki'])
carr = np.array(['AHAD','FAHAD','TINA','ZAKI'])
harr = np.array(["ahad",'fahad','tina','zaki'])
for i in range(len(larr)):
    larr[i]=larr[i].upper()
    harr[i]=harr[i].capitalize()
    carr[i]=carr[i].lower()
    
print(larr)
print(carr)
print(harr)

['AHAD' 'FAHAD' 'TINA' 'ZAKI']
['ahad' 'fahad' 'tina' 'zaki']
['Ahad' 'Fahad' 'Tina' 'Zaki']


In [49]:
arr = np.array(['hello','world'])
arr

array(['hello', 'world'], dtype='<U5')

In [51]:
upper = np.char.upper(arr)
upper

array(['HELLO', 'WORLD'], dtype='<U5')

In [53]:
lower = np.char.lower(upper)
lower

array(['hello', 'world'], dtype='<U5')

In [55]:
cap = np.char.capitalize(arr)
cap

array(['Hello', 'World'], dtype='<U5')

In [58]:
title = np.char.title(arr)
title

array(['Hello', 'World'], dtype='<U5')

In [57]:
swap = np.char.swapcase(cap)
swap

array(['hELLO', 'wORLD'], dtype='<U5')

#### Q. Get a row numbers of numpy array if any element is having larger value than a specific value

In [62]:
arr = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]))
np.shape(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [83]:
key = 13

np.any(arr > key,axis = 0)

array([False,  True,  True,  True])

In [77]:
np.where(np.any(arr > key,axis = 1))

(array([3], dtype=int64),)

3rd row is the answer

#### Q. How to remove rows which contain null value

In [84]:
array = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,np.nan,14,15],[16,17,18,19,20]))
array

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., nan, 14., 15.],
       [16., 17., 18., 19., 20.]])

In [85]:
 np.isnan(array)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [96]:
x = np.any(np.isnan(array),axis = 1)

array([False, False,  True, False])

In [90]:
np.where(np.any(np.isnan(array),axis = 1))

(array([2], dtype=int64),)

In [98]:
np.delete(array,2,axis = 0)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [16., 17., 18., 19., 20.]])

#### Q. How to multiply string element within a numpy

In [101]:
3 * "Fahad"

'FahadFahadFahad'

In [105]:
a = np.array(["Ahaa.."])\

x = np.char.multiply(a,3)
x

array(['Ahaa..Ahaa..Ahaa..'], dtype='<U18')

#### Q. How to Select minumum value along the rows

in axis = 0 mean we selecting rows and  axis = 0 means we selecting column

In [125]:
arr = np.random.randint(5,50,size=(5,5))
print(arr)

x = arr.min()
print(x)

np.where(np.any(arr == x, axis = 0))

[[39 14  7 22 23]
 [29 46  8 10 35]
 [42  7 45 15 28]
 [34 13 37 14  6]
 [44 21 33 18 33]]
6


(array([4], dtype=int64),)

5


array([False, False, False,  True,  True])

#### Q. Fill a diognal value with numpy array

In [168]:
varr = np.zeros((3,3))
varr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [169]:
for i in range(len(varr)):
    for j in range (len(varr[i])):
        if i == j: 
            varr[i,j] = 1
            break
        else:
            continue
        
varr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [155]:
brr = np.ones((3,3))
brr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [157]:
np.fill_diagonal(brr,0)
brr

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

#### Q. How to cheack if a number is present in numpy array and replace negative values with 999

In [186]:
arr = np.random.randint(-10,20,size = (3,3))
print("before\n",arr)
key = 7

for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i,j] < 0:
            arr[i,j] = 999
            
        if arr[i,j] == key:
            print(arr[i,j]," Element present",i+1,"row",j+1,"column")
            
print("after\n",arr) 

before
 [[ 2 16 -4]
 [-1  2 17]
 [-6 14  3]]
after
 [[  2  16 999]
 [999   2  17]
 [999  14   3]]


In [200]:
arry = np.random.randint(-10,20,size = (3,3))
print(arry)

print(np.isin(arry,7))


[[-1  7  6]
 [ 3 12 16]
 [ 1  8 16]]
[[False  True False]
 [False False False]
 [False False False]]


In [201]:
arry[arry < 0] = 999
arry

array([[999,   7,   6],
       [  3,  12,  16],
       [  1,   8,  16]])

#### Q.  Create a 4x4 random array and reshape it so the last row of previous array becomes the first row of new array and vice verca

In [202]:
arr = np.random.randint(10,size = (4,4))
arr

array([[3, 8, 0, 9],
       [7, 6, 6, 6],
       [5, 8, 4, 4],
       [8, 8, 5, 1]])

In [216]:
new_arr = arr[::-1,:]
new_arr

array([[8, 8, 5, 1],
       [5, 8, 4, 4],
       [7, 6, 6, 6],
       [3, 8, 0, 9]])

#### Q. Compare two numpy arrays

In [218]:
a = np.array(([1,2,3,4],[5,6,7,8]))
b = np.array(([2,1,4,5],[3,7,8,6]))

a > b

array([[False,  True, False, False],
       [ True, False, False,  True]])

In [220]:
np.greater(a,b)

array([[False,  True, False, False],
       [ True, False, False,  True]])

In [221]:
a>=b

array([[False,  True, False, False],
       [ True, False, False,  True]])

In [222]:
np.greater_equal(a,b)

array([[False,  True, False, False],
       [ True, False, False,  True]])

In [223]:
a < b

array([[ True, False,  True,  True],
       [False,  True,  True, False]])

In [224]:
np.less(a,b)

array([[ True, False,  True,  True],
       [False,  True,  True, False]])

#### Q. Stacking two arrays 


In [232]:
h1 = np.arange(10).reshape(2,5)
h2 = np.arange(11,21).reshape(2,5)

print(h1)
print(h2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [233]:
np.hstack([h1,h2])

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [236]:
v1 = np.random.randint(10,size = (3,3))
v2 = np.random.randint(10,30,size = (3,3))

print(v1)
print(v2)

[[0 7 5]
 [1 4 7]
 [3 4 3]]
[[26 15 29]
 [22 20 22]
 [11 12 22]]


In [241]:
np.vstack([v2,v1])

array([[26, 15, 29],
       [22, 20, 22],
       [11, 12, 22],
       [ 0,  7,  5],
       [ 1,  4,  7],
       [ 3,  4,  3]])

#### Q. How to Put elements at certain positions

In [250]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [251]:
arr2 = np.array([2,4,6])

arr.put([3,4,5],arr2)
arr

array([[0., 0., 0.],
       [2., 4., 6.],
       [0., 0., 0.]])

In [253]:
arr[2:,0:] = arr2
arr

array([[0., 0., 0.],
       [2., 4., 6.],
       [2., 4., 6.]])

#### Q. Delete a second column from a given array and insert the following new column in the place 

In [275]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [276]:
np.delete(a,1,axis=0)

array([[0, 1, 2],
       [6, 7, 8]])

In [277]:
b = np.array([77,78,79])
a[1:2,:] = b
a

array([[ 0,  1,  2],
       [77, 78, 79],
       [ 6,  7,  8]])

In [280]:
c = np.array([97,98,99])
np.insert(a,2,c,axis = 0)

array([[ 0,  1,  2],
       [77, 78, 79],
       [97, 98, 99],
       [ 6,  7,  8]])

#### Q. Wrtie a numpy profram to create 10 zeroes 10 ones and 10 fives


In [282]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [284]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [293]:
np.full((1,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])